# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwMNV4mKKhQLkbuss3UfgetAdKeRAAkU

# Новый раздел
"""

import matplotlib.pyplot as plt
import numpy as np

# Sinus funksiyasining grafigi
x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.figure(figsize=(12, 5))

# Chapdagi sinus grafigi
plt.subplot(1, 2, 1)
plt.plot(x, y, color='blue', label='Sinus(x)')
plt.title("Sinus Funksiyasining Grafigi")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")
plt.legend()
plt.grid()

# Tasodifiy nuqtalar grafigi
x_scatter = np.random.uniform(0, 10, 50)
y_scatter = np.random.uniform(0, 10, 50)

plt.subplot(1, 2, 2)
plt.scatter(x_scatter, y_scatter, color='purple', label='Nuqtalar')
plt.title("Tasodifiy Nuqtalar Scatter Grafigi")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")
plt.legend()
plt.grid()

plt.tight_layout()
plt.show()